# SNV+SV genotype PCA analysis with Plink, on GEUVADIS samples only

    # Prune genotypes in each super-population
    /Users/juanb/Documents/Bioinformatic_Tools/plink_mac_20200428/plink --vcf /Users/juanb/Desktop/2024_TE_GWAS_Juan/Code/1_GWAS_Analysis/2_Prepare_SNV_Genotype_Data/Combined_SNV_SV_Genotypes/AFR.SNVs.SVs.vcf.gz --keep /Users/juanb/Desktop/2024_TE_GWAS_Juan/Code/2_RNASeq_Analyses/0_All_Sample_Metadata_and_External_Resources/YRI_86_GEUV_and_Phase3_hg38.txt --double-id --allow-extra-chr --set-missing-var-ids @:# --indep-pairwise 50 10 0.1 --out Plink_YRI_PCA/Final_SNV_SV_YRI_pruned
    /Users/juanb/Documents/Bioinformatic_Tools/plink_mac_20200428/plink --vcf /Users/juanb/Desktop/2024_TE_GWAS_Juan/Code/1_GWAS_Analysis/2_Prepare_SNV_Genotype_Data/Combined_SNV_SV_Genotypes/EUR.SNVs.SVs.vcf.gz --keep /Users/juanb/Desktop/2024_TE_GWAS_Juan/Code/2_RNASeq_Analyses/0_All_Sample_Metadata_and_External_Resources/EUR_358_GEUV_and_Phase3_hg38.txt --double-id --allow-extra-chr --set-missing-var-ids @:# --indep-pairwise 50 10 0.1 --out Plink_EUR_PCA/Final_SNV_SV_EUR_pruned

    # Use the pruned data to run PCA analysis in each super-population
    /Users/juanb/Documents/Bioinformatic_Tools/plink_mac_20200428/plink --vcf /Users/juanb/Desktop/2024_TE_GWAS_Juan/Code/1_GWAS_Analysis/2_Prepare_SNV_Genotype_Data/Combined_SNV_SV_Genotypes/AFR.SNVs.SVs.vcf.gz --keep /Users/juanb/Desktop/2024_TE_GWAS_Juan/Code/2_RNASeq_Analyses/0_All_Sample_Metadata_and_External_Resources/YRI_86_GEUV_and_Phase3_hg38.txt --double-id --allow-extra-chr --set-missing-var-ids @:# --extract Plink_YRI_PCA/Final_SNV_SV_YRI_pruned.prune.in --pca var-wts --out Plink_YRI_PCA/Final_SNV_SV_YRI_PCA
    /Users/juanb/Documents/Bioinformatic_Tools/plink_mac_20200428/plink --vcf /Users/juanb/Desktop/2024_TE_GWAS_Juan/Code/1_GWAS_Analysis/2_Prepare_SNV_Genotype_Data/Combined_SNV_SV_Genotypes/EUR.SNVs.SVs.vcf.gz --keep /Users/juanb/Desktop/2024_TE_GWAS_Juan/Code/2_RNASeq_Analyses/0_All_Sample_Metadata_and_External_Resources/EUR_358_GEUV_and_Phase3_hg38.txt --double-id --allow-extra-chr --set-missing-var-ids @:# --extract Plink_EUR_PCA/Final_SNV_SV_EUR_pruned.prune.in --pca var-wts --out Plink_EUR_PCA/Final_SNV_SV_EUR_PCA
